.PHONY: help
help:
	@echo "poetry-config      : Configure poetry"
	@echo "install-package    : Install the package `{{package_name}}` and its dependencies"
{%- if include_precommit %}	
	@echo "pre-commit-install : Install pre-commit hooks"
	@echo "pre-commit         : Run pre-commit"
{%- endif %}
	@echo "setup              : Set up the project, assuming poetry is installed"

.PHONY: poetry-config
poetry-config:
	poetry config virtualenvs.in-project true

.PHONY: install-package
install-package:
	poetry install $(test "$YOUR_ENV" = PRD && echo "--no-dev")
{% if include_precommit %}
.PHONY: pre-commit-install
pre-commit-install:
	poetry run pre-commit install

.PHONY: pre-commit
pre-commit:
	poetry run pre-commit run -a
{% endif %}
.PHONY: setup
setup: poetry-config install-package {% if include_precommit %}pre-commit-install{% endif %}
