repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
      - args: ["--disallow-untyped-defs"]
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        name: Run black formatter
        language_version: python3.9
  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-all-unused-imports"]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        name: Run flake8 linter
        additional_dependencies:
          ["flake8-bugbear==20.11.1", "pep8-naming==0.11.1"]
        args: ["--max-line-length", "88"]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.11.3
    hooks:
      - id: isort
        additional_dependencies: [toml]
        name: Sort imports using isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        name: Check for code that can use new Python features
        args: [--py38-plus]
